### ISSUE TITLE
InvalidArgumentError for actor input with DDPG agent

### ISSUE THREAD

**Issue by mattdornfeld** [keras-rl/keras-rl#183]
Below is the full traceback. It seems that some part of the Tensorflow graph is expecting data to be fed into the actor inputs.

```
python3 train/train.py 
Using TensorFlow backend.
2018-03-25 18:02:26.208844: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Training for 10 steps ...
Interval 1 (0 steps performed)
 6/10 [=================>............] - ETA: 3s - reward: 0.0000e+00Traceback (most recent call last):
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'actor_input' with dtype float and shape [?,3,?,7]
	 [[Node: actor_input = Placeholder[dtype=DT_FLOAT, shape=[?,3,?,7], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train/train.py", line 157, in <module>
    agent.fit(env = env, nb_steps = 10, log_interval = 10)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/rl/core.py", line 185, in fit
    metrics = self.backward(reward, terminal=done)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/rl/agents/ddpg.py", line 315, in backward
    action_values = self.actor_train_fn(inputs)[0]
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2478, in __call__
    **self.session_kwargs)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'actor_input' with dtype float and shape [?,3,?,7]
	 [[Node: actor_input = Placeholder[dtype=DT_FLOAT, shape=[?,3,?,7], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'actor_input', defined at:
  File "train/train.py", line 116, in <module>
    num_cells_merge_branch=3)
  File "/home/matthew/projects/bitcoin_trader/train/model.py", line 67, in build_actor
    name = 'actor_input')
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/keras/engine/topology.py", line 1457, in Input
    input_tensor=tensor)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/keras/engine/topology.py", line 1366, in __init__
    name=self.name)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 507, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3141, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/matthew/projects/bitcoin_trader/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'actor_input' with dtype float and shape [?,3,?,7]
	 [[Node: actor_input = Placeholder[dtype=DT_FLOAT, shape=[?,3,?,7], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


```

I've traced the problem to this portion of the code in the DDPG agent

```
        updates = actor_optimizer.get_updates(
            params=self.actor.trainable_weights, loss=-K.mean(combined_output))
        if self.target_model_update < 1.:
            # Include soft target model updates.
            updates += get_soft_target_model_updates(self.target_actor, self.actor, self.target_model_update)
        updates += self.actor.updates  # include other updates of the actor, e.g. for BN```
```
If I comment the line, updates += self.actor.updates, the problem the dissapears. Does anyone know what that line does? Is it necessary?

**Comment by tat-dat** [comment]
I have the same problem, does anyone have the solution or explanation?
