### ISSUE TITLE
DQN with BoltzmannQPolicy failing with `get_updates() missing 1 required positional argument: 'constraints'`

### ISSUE THREAD

**Issue by redknightlois** [keras-rl/keras-rl#189]
Base code works properly with CEM but fails when running DQNAgent.

```
Traceback (most recent call last):
  File "E:/Src/trendstone-git/src/learner-v2/main.py", line 140, in <module>
    agent.fit(env, nb_steps=500000, visualize=False, verbose=2)
  File "E:\Src\keras-rl-git\rl\core.py", line 185, in fit
    metrics = self.backward(reward, terminal=done)
  File "E:\Src\keras-rl-git\rl\agents\dqn.py", line 314, in backward
    metrics = self.trainable_model.train_on_batch(ins + [targets, masks], [dummy_targets, targets])
  File "C:\Anaconda3\lib\site-packages\keras\engine\training.py", line 1882, in train_on_batch
    self._make_train_function()
  File "C:\Anaconda3\lib\site-packages\keras\engine\training.py", line 990, in _make_train_function
    loss=self.total_loss)
TypeError: get_updates() missing 1 required positional argument: 'constraints'
```

The code I am using to execute looks like this:

```
    memory = SequentialMemory(limit=50000, window_length=1)
    policy = BoltzmannQPolicy()
    agent = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=1000,
                     enable_dueling_network=True, dueling_type='max', target_model_update=1e-2, policy=policy)
    agent.compile(keras.optimizers.Adadelta(), metrics=['mae'])
    agent.fit(env, nb_steps=500000, visualize=False, verbose=2)
    agent.save_weights(f'dqn_{random.randint(0, 100000)}_weights.h5f', overwrite=True)
```

- [x] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/keras-rl/keras-rl.git --upgrade --no-deps`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

**Comment by redknightlois** [comment]
Latest for all of them from source. In my code with an slightly more complex model but give or take the same code as cart-pole

```python
    input = Input(shape=(1, obs_dim,), name='input') 
    m = keras.layers.Dense(units=16, activation='relu')(input) 
    m = keras.layers.Dense(units=16, activation='relu')(m) 
    m = keras.layers.Dense(units=16, activation='relu')(m) 
    m = keras.layers.Flatten()(m) 
    m = keras.layers.Dense(output_dim=nb_actions, activation='softmax')(m) 
 
    model = Model(inputs=input, outputs=m) 
    model.summary() 
```

Check also that I tried to compile with AdaDelta. BTW ```verbose=1``` fails consistently too.

**Comment by dickreuter** [comment]
I'm experiencing the same problem. Example code can be found here:
https://github.com/dickreuter/neuron_poker
when running
`main.py deep_q_learning`

**Comment by dickreuter** [comment]
Found the problem: When a custom processor is passed into the model, the class needs to be instantiated.
