### ISSUE TITLE
History object is not properly formatted for json

### ISSUE THREAD

**Issue by mirfan899** [keras-rl/keras-rl#270]
When I want to save the history json object it throws errors.

```python
with open('dqn_cartpole_history_no_noise.json', 'w') as f:
    json.dump(history.history, f)
```
Error:

```shell
Testing for 5 episodes ...
Episode 1: reward: 200.000, steps: 200
Episode 2: reward: 200.000, steps: 200
Episode 3: reward: 200.000, steps: 200
Episode 4: reward: 200.000, steps: 200
Episode 5: reward: 200.000, steps: 200
Traceback (most recent call last):
  File "dqn_cartpole.py", line 58, in <module>
    json.dump(history.history, f)
  File "/usr/lib/python3.5/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 31 is not JSON serializable
```
I tried to use `simplejson` it also throws error:
```shell
Testing for 5 episodes ...
Episode 1: reward: 139.000, steps: 139
Episode 2: reward: 123.000, steps: 123
Episode 3: reward: 120.000, steps: 120
Episode 4: reward: 171.000, steps: 171
Episode 5: reward: 122.000, steps: 122
Traceback (most recent call last):
  File "dqn_cartpole.py", line 58, in <module>
    json.dump(history.history, f)
  File "/home/imran/PycharmProjects/k/.k/lib/python3.5/site-packages/simplejson/__init__.py", line 278, in dump
    for chunk in iterable:
  File "/home/imran/PycharmProjects/k/.k/lib/python3.5/site-packages/simplejson/encoder.py", line 696, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/home/imran/PycharmProjects/k/.k/lib/python3.5/site-packages/simplejson/encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "/home/imran/PycharmProjects/k/.k/lib/python3.5/site-packages/simplejson/encoder.py", line 531, in _iterencode_list
    for chunk in chunks:
  File "/home/imran/PycharmProjects/k/.k/lib/python3.5/site-packages/simplejson/encoder.py", line 716, in _iterencode
    o = _default(o)
  File "/home/imran/PycharmProjects/k/.k/lib/python3.5/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
```
Also strings are in single quote `''` it should be in double quotes `""`
```json
{
  'episode_reward': [
    31.0,
    23.0,
    25.0,
    20.0,
    11.0,
    27.0,
    20.0,
    18.0,
    44.0,
    9.0,
    10.0,
    11.0,
    33.0,
    18.0,
    14.0,
    11.0,
    32.0,
    10.0,
    19.0,
    23.0,
    24.0,
    14.0,
    23.0,
    13.0,
    10.0,
    23.0,
    23.0,
    19.0,
    10.0,
    17.0,
    17.0,
    10.0,
    10.0,
    14.0,
    12.0,
    18.0,
    13.0,
    14.0,
    38.0,
    63.0,
    24.0,
    26.0,
    16.0,
    26.0,
    13.0,
    44.0,
    43.0,
    25.0,
    44.0,
    34.0,
    34.0,
    37.0,
    93.0,
    18.0,
    103.0,
    55.0,
    113.0,
    126.0,
    113.0,
    146.0,
    175.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    177.0,
    181.0,
    200.0,
    195.0,
    200.0,
    173.0,
    173.0,
    200.0,
    200.0,
    175.0,
    200.0,
    192.0,
    195.0,
    200.0,
    159.0,
    178.0,
    200.0,
    200.0,
    200.0,
    188.0,
    200.0,
    200.0,
    185.0,
    183.0,
    200.0,
    170.0,
    200.0,
    150.0,
    200.0,
    173.0,
    200.0,
    200.0,
    181.0,
    192.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    180.0,
    162.0,
    200.0,
    197.0,
    200.0,
    123.0,
    200.0,
    156.0,
    143.0,
    200.0,
    200.0,
    181.0,
    200.0,
    200.0,
    127.0,
    170.0,
    179.0,
    173.0,
    200.0,
    200.0,
    196.0,
    134.0,
    155.0,
    200.0,
    124.0,
    142.0,
    200.0,
    174.0,
    140.0,
    155.0,
    155.0,
    147.0,
    200.0,
    160.0,
    200.0,
    129.0,
    173.0,
    144.0,
    175.0,
    200.0,
    158.0,
    188.0,
    200.0,
    200.0,
    192.0,
    182.0,
    200.0,
    176.0,
    200.0,
    200.0,
    200.0,
    178.0,
    189.0,
    148.0,
    148.0,
    192.0,
    156.0,
    199.0,
    170.0,
    200.0,
    166.0,
    200.0,
    171.0,
    171.0,
    154.0,
    200.0,
    200.0,
    171.0,
    193.0,
    183.0,
    178.0,
    171.0,
    200.0,
    177.0,
    200.0,
    200.0,
    200.0,
    187.0,
    200.0,
    200.0,
    189.0,
    166.0,
    200.0,
    187.0,
    200.0,
    197.0,
    200.0,
    200.0,
    179.0,
    194.0,
    188.0,
    195.0,
    200.0,
    188.0,
    180.0,
    198.0,
    171.0,
    200.0,
    184.0,
    195.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    194.0,
    200.0,
    188.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    197.0,
    200.0,
    200.0,
    200.0,
    200.0,
    192.0,
    200.0,
    200.0,
    196.0,
    200.0,
    168.0,
    200.0,
    200.0,
    200.0,
    200.0,
    200.0,
    169.0,
    177.0,
    200.0,
    200.0,
    200.0,
    200.0,
    164.0
  ],
  'nb_episode_steps': [
    31,
    23,
    25,
    20,
    11,
    27,
    20,
    18,
    44,
    9,
    10,
    11,
    33,
    18,
    14,
    11,
    32,
    10,
    19,
    23,
    24,
    14,
    23,
    13,
    10,
    23,
    23,
    19,
    10,
    17,
    17,
    10,
    10,
    14,
    12,
    18,
    13,
    14,
    38,
    63,
    24,
    26,
    16,
    26,
    13,
    44,
    43,
    25,
    44,
    34,
    34,
    37,
    93,
    18,
    103,
    55,
    113,
    126,
    113,
    146,
    175,
    200,
    200,
    200,
    200,
    200,
    200,
    177,
    181,
    200,
    195,
    200,
    173,
    173,
    200,
    200,
    175,
    200,
    192,
    195,
    200,
    159,
    178,
    200,
    200,
    200,
    188,
    200,
    200,
    185,
    183,
    200,
    170,
    200,
    150,
    200,
    173,
    200,
    200,
    181,
    192,
    200,
    200,
    200,
    200,
    200,
    200,
    180,
    162,
    200,
    197,
    200,
    123,
    200,
    156,
    143,
    200,
    200,
    181,
    200,
    200,
    127,
    170,
    179,
    173,
    200,
    200,
    196,
    134,
    155,
    200,
    124,
    142,
    200,
    174,
    140,
    155,
    155,
    147,
    200,
    160,
    200,
    129,
    173,
    144,
    175,
    200,
    158,
    188,
    200,
    200,
    192,
    182,
    200,
    176,
    200,
    200,
    200,
    178,
    189,
    148,
    148,
    192,
    156,
    199,
    170,
    200,
    166,
    200,
    171,
    171,
    154,
    200,
    200,
    171,
    193,
    183,
    178,
    171,
    200,
    177,
    200,
    200,
    200,
    187,
    200,
    200,
    189,
    166,
    200,
    187,
    200,
    197,
    200,
    200,
    179,
    194,
    188,
    195,
    200,
    188,
    180,
    198,
    171,
    200,
    184,
    195,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    194,
    200,
    188,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    200,
    197,
    200,
    200,
    200,
    200,
    192,
    200,
    200,
    196,
    200,
    168,
    200,
    200,
    200,
    200,
    200,
    169,
    177,
    200,
    200,
    200,
    200,
    164
  ],
  'nb_steps': [
    31,
    54,
    79,
    99,
    110,
    137,
    157,
    175,
    219,
    228,
    238,
    249,
    282,
    300,
    314,
    325,
    357,
    367,
    386,
    409,
    433,
    447,
    470,
    483,
    493,
    516,
    539,
    558,
    568,
    585,
    602,
    612,
    622,
    636,
    648,
    666,
    679,
    693,
    731,
    794,
    818,
    844,
    860,
    886,
    899,
    943,
    986,
    1011,
    1055,
    1089,
    1123,
    1160,
    1253,
    1271,
    1374,
    1429,
    1542,
    1668,
    1781,
    1927,
    2102,
    2302,
    2502,
    2702,
    2902,
    3102,
    3302,
    3479,
    3660,
    3860,
    4055,
    4255,
    4428,
    4601,
    4801,
    5001,
    5176,
    5376,
    5568,
    5763,
    5963,
    6122,
    6300,
    6500,
    6700,
    6900,
    7088,
    7288,
    7488,
    7673,
    7856,
    8056,
    8226,
    8426,
    8576,
    8776,
    8949,
    9149,
    9349,
    9530,
    9722,
    9922,
    10122,
    10322,
    10522,
    10722,
    10922,
    11102,
    11264,
    11464,
    11661,
    11861,
    11984,
    12184,
    12340,
    12483,
    12683,
    12883,
    13064,
    13264,
    13464,
    13591,
    13761,
    13940,
    14113,
    14313,
    14513,
    14709,
    14843,
    14998,
    15198,
    15322,
    15464,
    15664,
    15838,
    15978,
    16133,
    16288,
    16435,
    16635,
    16795,
    16995,
    17124,
    17297,
    17441,
    17616,
    17816,
    17974,
    18162,
    18362,
    18562,
    18754,
    18936,
    19136,
    19312,
    19512,
    19712,
    19912,
    20090,
    20279,
    20427,
    20575,
    20767,
    20923,
    21122,
    21292,
    21492,
    21658,
    21858,
    22029,
    22200,
    22354,
    22554,
    22754,
    22925,
    23118,
    23301,
    23479,
    23650,
    23850,
    24027,
    24227,
    24427,
    24627,
    24814,
    25014,
    25214,
    25403,
    25569,
    25769,
    25956,
    26156,
    26353,
    26553,
    26753,
    26932,
    27126,
    27314,
    27509,
    27709,
    27897,
    28077,
    28275,
    28446,
    28646,
    28830,
    29025,
    29225,
    29425,
    29625,
    29825,
    30025,
    30225,
    30425,
    30625,
    30825,
    31025,
    31225,
    31425,
    31625,
    31825,
    32025,
    32225,
    32425,
    32625,
    32825,
    33025,
    33225,
    33425,
    33625,
    33825,
    34019,
    34219,
    34407,
    34607,
    34807,
    35007,
    35207,
    35407,
    35607,
    35807,
    36007,
    36207,
    36407,
    36607,
    36807,
    37007,
    37207,
    37407,
    37607,
    37807,
    38007,
    38207,
    38407,
    38607,
    38807,
    39007,
    39207,
    39407,
    39607,
    39807,
    40007,
    40207,
    40407,
    40607,
    40807,
    41007,
    41207,
    41407,
    41607,
    41807,
    42007,
    42207,
    42407,
    42607,
    42807,
    43007,
    43207,
    43407,
    43607,
    43807,
    44007,
    44207,
    44407,
    44607,
    44807,
    45007,
    45207,
    45407,
    45604,
    45804,
    46004,
    46204,
    46404,
    46596,
    46796,
    46996,
    47192,
    47392,
    47560,
    47760,
    47960,
    48160,
    48360,
    48560,
    48729,
    48906,
    49106,
    49306,
    49506,
    49706,
    49870
  ]
}
```

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/keras-rl/keras-rl.git --upgrade --no-deps`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

**Comment by gvgramazio** [comment]
Why don't you use one of the already provided callbacks to store your stats or define a new one? I tried to modify FileLogger and there are no problems at all with `.json` files.

**Comment by RaphaelMeudec** [comment]
Indeed, you should check out the `FileLogger` callback for instance
