### ISSUE TITLE
DDPG on Discrete Action Space

### ISSUE THREAD

**Issue by Psyf** [keras-rl/keras-rl#285]
Hi. 

I wanted to train an Actor-Critic on the Cartpole Environment (new Deel RL student here :) )
I know that sounds overkill, I just wanted to try. 

This is my actor: 
```
observation = Input(shape=(1, ) + env.observation_space.shape)
x = Dense(16, activation='relu')(observation)
x = Dense(16, activation='relu')(x)
x = Dense(16, activation='relu')(x)
x = Dense(num_actions, activation='linear')(x)	
actor_output = Reshape((num_actions, ))(x)
actor = Model(inputs=observation, outputs=actor_output)
```

However, this is what happens when I try to run the file: 
```
Training for 100000 steps ...
Traceback (most recent call last):
  File "A2C_cartpole.py", line 47, in <module>
    agent.fit(env, nb_steps=100000, verbose=2, callbacks=[tb])
  File "C:\Users\Psyf\Anaconda3\envs\NeuralStyleTransfer\lib\site-packages\rl\core.py", line 177, in fit
    observation, r, done, info = env.step(action)
  File "C:\Users\Psyf\Anaconda3\envs\NeuralStyleTransfer\lib\site-packages\gym\wrappers\time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "C:\Users\Psyf\Anaconda3\envs\NeuralStyleTransfer\lib\site-packages\gym\envs\classic_control\cartpole.py", line 92, in step
    assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
AssertionError: array([-0.00089871, -0.00465946], dtype=float32) (<class 'numpy.ndarray'>) invalid
```

From what I understand, the error is occurring since the Actor is outputting floating points, and the env expects a one-hot encoded vector when calling env.step(action). 

Does anybody know a workaround? Currently, I'm thinking of modifying ddpg.py and change `select_action()` to loop through the output and output either a [1, 0] or a [0, 1] for the cartpole. 
Please advise. 

Thanks and Best Regards.

**Comment by King-Of-Knights** [comment]
Hi, I believe the last layer activation of your actor should be "softmax" if you wish to conduct Discrete Action

**Comment by WHui829129** [comment]
Hi.
I wanted to train an DQN on the Minist dataset for image classification, how to build my environment?
Thank you!

**Comment by zh3389** [comment]
在源码文件路径中`?\site-packages\rl\core.py`的`177行`添加`action = np.argmax(action)`即可正常训练离散动作的代理,如果要训练连续动作的代理.则需要注释掉`action = np.argmax(action)`


```
for _ in range(action_repetition):  
     callbacks.on_action_begin(action) 
     # 此处添加 action = np.argmax(action)
     action = np.argmax(action)  
     observation, r, done, info = env.step(action)  
     observation = deepcopy(observation)
```

测试的时候会出现同样的错误, 同样在大概 300 多行左右. 也就是报错的位置添加`action = np.argmax(action)`即可

**Comment by Mrzhang3389** [comment]
虽然代码能正常运行了, 但是代理好像还是不能被正常训练..   代理完全就没有动作了.

**Comment by Mrzhang3389** [comment]
测试的时候会出现同样的错误, 同样在大概 300 多行左右. 也就是报错的位置添加`action = np.argmax(action)`即可
