### ISSUE TITLE
NAFAgent bug?

### ISSUE THREAD

**Issue by Amndeep7** [keras-rl/keras-rl#313]
Getting an issue where both the NAFAgent based example and test are failing due to shape mismatches.  

```
amn@amn-VirtualBox:~/tensorflow_examples/keras-rl/tests/integration$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_continuous
Using TensorFlow backend.
>>> test_continuous.test_cdqn()
WARNING:tensorflow:From /home/amn/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-04-29 15:28:47.368705: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-29 15:28:47.378627: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592005000 Hz
2019-04-29 15:28:47.378966: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x22c0740 executing computations on platform Host. Devices:
2019-04-29 15:28:47.380579: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amn/tensorflow_examples/keras-rl/tests/integration/test_continuous.py", line 48, in test_cdqn
    agent.compile(Adam(lr=1e-3))
  File "/home/amn/.local/lib/python3.6/site-packages/rl/agents/dqn.py", line 615, in compile
    A_out = NAFLayer(self.nb_actions, mode=self.covariance_mode)([L_out, mu_out, a_in])
  File "/home/amn/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/amn/.local/lib/python3.6/site-packages/rl/agents/dqn.py", line 433, in call
    L_flat = tf.concat(1, [zeros, L_flat])
  File "/home/amn/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/amn/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1254, in concat
    tensor_shape.scalar())
  File "/home/amn/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1023, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, ?, 1) and () are incompatible
```

The test passed when I ran it with pytest but I thought something might've been up due to it running in literally 0 time whereas the other test in the file took around 20s.

**Comment by AlexanderTreyer** [comment]
@Amndeep7 Have same problem. Do you know how to solve it?

**Comment by Amndeep7** [comment]
@AlexanderTreyer yeah, I used a different agent haha

**Comment by RomanKisilenko** [comment]
I think this is still actual for many of us.

**Comment by pidipidi** [comment]
I have the same issue.

**Comment by bvrockwell** [comment]
i have the same issue as well.

**Comment by Raphtor** [comment]
I got it to work by installing via github instead of pypi.
