### ISSUE TITLE
Help! Memory error!

### ISSUE THREAD

**Issue by TianLin0509** [keras-rl/keras-rl#319]
Hello, I use the keras-rl and run the dqn_cartpole.py successfully. 
Then I change the env_name to play the Pong game, i.e., env_name = "PongNoFrameskip-v4".
All thing looks good, however, the program break suddenly with Memory Error, as shown in the following:

```
Traceback (most recent call last):
  File "D:/github_repos/keras-rl-master/examples/dqn_cartpole.py", line 47, in <module>
    dqn.fit(env, nb_steps=500000, visualize=True, verbose=2)
  File "D:\github_repos\keras-rl-master\rl\core.py", line 224, in fit
    callbacks.on_episode_end(episode, episode_logs)
  File "D:\github_repos\keras-rl-master\rl\callbacks.py", line 67, in on_episode_end
    callback.on_episode_end(episode, logs=logs)
  File "D:\github_repos\keras-rl-master\rl\callbacks.py", line 191, in on_episode_end
    'obs_mean': np.mean(self.observations[episode]),
  File "C:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 2920, in mean
    out=out, **kwargs)
  File "C:\Anaconda3\lib\site-packages\numpy\core\_methods.py", line 59, in _mean
    arr = asanyarray(a)
  File "C:\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 553, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
MemoryError

```

As I use the 1080Ti and 48G RAM， I'm really puzzled about the result. 
What cause the problem?

**Comment by kanchi0914** [comment]
why don't you use dqn_atari.py instead of dqn_cartpole.py?
Environment of Atari game such as Pong  returns image information, so we should build network like CNN dedicated to them.   
It used raw information of Environment in dqn_cartpole.py, and I think you cannot use it as it is.
Moreover, Atari Environment sometimes needs some installation different from gym package. You may want to check some lack of them.  
Good luck.
