### ISSUE TITLE
C:\Python\Python37\lib\site-packages\keras_rl-0.4.2-py3.7.egg\rl\agents\dqn.py in __init__(self, model, policy, test_policy, enable_double_dqn, enable_dueling_network, dueling_type, *args, **kwargs)

### ISSUE THREAD

**Issue by shravansuthar210** [keras-rl/keras-rl#374]
C:\Python\Python37\lib\site-packages\keras_rl-0.4.2-py3.7.egg\rl\agents\dqn.py in __init__(self, model, policy, test_policy, enable_double_dqn, enable_dueling_network, dueling_type, *args, **kwargs)
    106 
    107         # Validate (important) input.
--> 108         if hasattr(model.output, '__len__') and len(model.output) > 1:
    109             raise ValueError('Model "{}" has more than one output. DQN expects a model that has a single output.'.format(model))
    110         if model.output._keras_shape != (None, self.nb_actions):

C:\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\keras_tensor.py in __len__(self)
    238 
    239   def __len__(self):
--> 240     raise TypeError('Keras symbolic inputs/outputs do not '
    241                     'implement `__len__`. You may be '
    242                     'trying to pass Keras symbolic inputs/outputs '

TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.

please help me .....

_Originally posted by @Shravansuthar211 in https://github.com/keras-rl/keras-rl/issues/348#issuecomment-777403033_

**Comment by vadim0x60** [comment]
I have the same issue. Minimal script to reproduce it:

```
import gym
import click

from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.optimizers import Adam

from rl.agents.dqn import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory

def train(env):
    nb_actions = env.action_space.n

    # Next, we build a very simple model.
    model = Sequential()
    model.add(Flatten(input_shape=(1,) + env.observation_space.shape))
    model.add(Dense(16))
    model.add(Activation('relu'))
    model.add(Dense(16))
    model.add(Activation('relu'))
    model.add(Dense(16))
    model.add(Activation('relu'))
    model.add(Dense(nb_actions))
    model.add(Activation('linear'))
    print(model.summary())

    # Finally, we configure and compile our agent. You can use every built-in Keras optimizer and
    # even the metrics!
    memory = SequentialMemory(limit=50000, window_length=1)
    policy = BoltzmannQPolicy()
    dqn = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=10,
                target_model_update=1e-2, policy=policy)
    dqn.compile(Adam(lr=1e-3), metrics=['mae'])

    # Okay, now it's time to learn something! We visualize the training here for show, but this
    # slows down training quite a lot. You can always safely abort the training prematurely using
    # Ctrl + C.
    dqn.fit(env, nb_steps=50000, visualize=True, verbose=2)
    return dqn

@click.command()
@click.argument('env_name')
def main(env_name):
    env = gym.make(env_name)
    dqn = train(env)

    # After training is done, we save the final weights.
    dqn.save_weights('dqn_weights.h5f', overwrite=True)

    # Finally, evaluate our algorithm for 5 episodes.
    dqn.test(env, nb_episodes=5, visualize=True)

if __name__ == '__main__':
    main()
```

Environment:

```
click==7.1.2
tensorflow==2.4.1
keras-rl==0.4.2
gym==0.17.3
```

Error:

```
Traceback (most recent call last):
  File "keras_rl_solve.py", line 67, in <module>
    main()
  File "/home/vadim0x60/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vadim0x60/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vadim0x60/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vadim0x60/.pyenv/versions/3.8.6/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "keras_rl_solve.py", line 58, in main
    dqn = train(env)
  File "keras_rl_solve.py", line 35, in train
    dqn = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=10,
  File "/home/vadim0x60/.pyenv/versions/3.8.6/lib/python3.8/site-packages/rl/agents/dqn.py", line 108, in __init__
    if hasattr(model.output, '__len__') and len(model.output) > 1:
  File "/home/vadim0x60/.pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/python/keras/engine/keras_tensor.py", line 240, in __len__
    raise TypeError('Keras symbolic inputs/outputs do not '
TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.
```

**Comment by vadim0x60** [comment]
I tried `CartPole-v0`, `MountainCar-v1` and `Taxi-v3`

**Comment by mpoehlmann** [comment]
I have the same issue. It occurs when running `examples/dqn_cartpole.py`.
