### ISSUE TITLE
AttributeError: Tensor.op is meaningless when eager execution is enabled.

### ISSUE THREAD

**Issue by 2462370039** [keras-rl/keras-rl#399]
When I run example: dqn_cartpole.py, I get this error: 
----------
Training for 50000 steps ...
2024-07-11 19:28:59.111713: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
E:\Anaconda3\envs\py36\lib\site-packages\rl\memory.py:39: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')
Traceback (most recent call last):
  File "f:/Coding/paperCoding/RL/DQN/dqn_cartpole.py", line 46, in <module>
    dqn.fit(env, nb_steps=50000, visualize=True, verbose=2)
  File "E:\Anaconda3\envs\py36\lib\site-packages\rl\core.py", line 194, in fit
    metrics = self.backward(reward, terminal=done)
  File "E:\Anaconda3\envs\py36\lib\site-packages\rl\agents\dqn.py", line 325, in backward
    metrics = self.trainable_model.train_on_batch(ins + [targets, masks], [dummy_targets, targets])
  File "E:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 1513, in train_on_batch
    self._make_train_function()
  File "E:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 333, in _make_train_function
    **self._function_kwargs)
  File "E:\Anaconda3\envs\py36\lib\site-packages\keras\backend\tensorflow_backend.py", line 3009, in function
    **kwargs)
  File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3760, in function
    return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
  File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3657, in __init__
    base_graph=source_graph)
  File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\lift_to_graph.py", line 260, in lift_to_graph
    add_sources=add_sources))
  File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\ops\op_selector.py", line 393, in map_subgraph
    ops_to_visit = [_as_operation(init_tensor)]
  File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\ops\op_selector.py", line 320, in _as_operation
    return op_or_tensor.op
  File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1094, in op
    "Tensor.op is meaningless when eager execution is enabled.")
AttributeError: Tensor.op is meaningless when eager execution is enabled.
How do i fix this error?

**Comment by 2462370039** [comment]
```
Training for 50000 steps ...
2024-07-11 19:28:59.111713: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
E:\Anaconda3\envs\py36\lib\site-packages\rl\memory.py:39: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')
Traceback (most recent call last):
File "f:/Coding/paperCoding/RL/DQN/dqn_cartpole.py", line 46, in
dqn.fit(env, nb_steps=50000, visualize=True, verbose=2)
File "E:\Anaconda3\envs\py36\lib\site-packages\rl\core.py", line 194, in fit
metrics = self.backward(reward, terminal=done)
File "E:\Anaconda3\envs\py36\lib\site-packages\rl\agents\dqn.py", line 325, in backward
metrics = self.trainable_model.train_on_batch(ins + [targets, masks], [dummy_targets, targets])
File "E:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 1513, in train_on_batch
self._make_train_function()
File "E:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 333, in _make_train_function
**self._function_kwargs)
File "E:\Anaconda3\envs\py36\lib\site-packages\keras\backend\tensorflow_backend.py", line 3009, in function
**kwargs)
File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3760, in function
return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3657, in init
base_graph=source_graph)
File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\eager\lift_to_graph.py", line 260, in lift_to_graph
add_sources=add_sources))
File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\ops\op_selector.py", line 393, in map_subgraph
ops_to_visit = [_as_operation(init_tensor)]
File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\ops\op_selector.py", line 320, in _as_operation
return op_or_tensor.op
File "E:\Anaconda3\envs\py36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1094, in op
"Tensor.op is meaningless when eager execution is enabled.")
AttributeError: Tensor.op is meaningless when eager execution is enabled.
```
