### ISSUE TITLE
can't run code after calling test funcion

### ISSUE THREAD

**Issue by rola93** [keras-rl/keras-rl#98]
Hello!
I implemented a function to save status as jpg on train mode, I was going to do a pull request, but when I tested it in a different machine it doesn't run.

whatever I execute into def test(...) in core.py isn't executed: raise Exception, print "this code is reachable" or exit.

I tried to debug it using prints but as soon as execution goes into def test(...), print starts to be ignored.

Any idea? [This version](https://github.com/rola93/keras-rl) runs well locally, but in others machines it didn't work.

thanks in advance

**Comment by matthiasplappert** [comment]
What exactly happens if you run the test method? Does it raise an exception or trigger an assertion? If so, can you please paste the entire output here?

**Comment by chairbender** [comment]
I think I have this issue as well.

I call the agent.test method and it just freezes, seemingly randomly. Sometimes in runs for a few iterations of train-test, then freezes. Other times it freezes right away. I'm not sure what is changing that causes this difference.

When I interrupt it, I get the following traceback:
Traceback (most recent call last):
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/scratchpad.py", line 16, in <module>
    agent.learn(plot=True)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/fantasy_football_auction_ai/agents.py", line 102, in learn
    history = agent.test(self.env, nb_episodes=test_episodes, verbose=1, visualize=False, callbacks=plot_callbacks).history
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/core.py", line 307, in test
    action = self.forward(observation)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/agents/dqn.py", line 217, in forward
    q_values = self.compute_q_values(state)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/agents/dqn.py", line 69, in compute_q_values
    q_values = self.compute_batch_q_values([state]).flatten()
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/agents/dqn.py", line 64, in compute_batch_q_values
    q_values = self.model.predict_on_batch(batch)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1902, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2357, in __call__
    **self.session_kwargs)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
KeyboardInterrupt

**Comment by chairbender** [comment]
Okay, here's some more details.

I'm on Ubuntu 16.04. Running tensorflow backend on CPU.

Check out my repo here to reproduce this: https://github.com/chairbender/fantasy-football-auction-ai. Follow the instructions in the README to run learn.py. Maybe it only happens on my PC?

The behavior I see is that it completes a few cycles of train and then test, then eventually freezes on agent.test after 1-8 cycles. No errors reported. Interrupting it produces the stack trace shown below (the one above is when I tried running on tensorflow-gpu):
````
Traceback (most recent call last):
  File "learn.py", line 16, in <module>
    agent.learn(plot=True)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/fantasy_football_auction_ai/agents.py", line 102, in learn
    history = agent.test(self.env, nb_episodes=test_episodes, verbose=0, visualize=False, callbacks=plot_callbacks).history
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/core.py", line 307, in test
    action = self.forward(observation)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/agents/dqn.py", line 217, in forward
    q_values = self.compute_q_values(state)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/agents/dqn.py", line 69, in compute_q_values
    q_values = self.compute_batch_q_values([state]).flatten()
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/rl/agents/dqn.py", line 64, in compute_batch_q_values
    q_values = self.model.predict_on_batch(batch)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1902, in predict_on_batch
(venv) kwhipke1@kwhipke1-System-Product-Name:~/PycharmProjects/fantasy-football-auction-ai$     outputs = self.predict_function(ins)
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2355, in __call__
    session = get_session()
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 172, in get_session
    with session.graph.as_default():
  File "/home/kwhipke1/PycharmProjects/fantasy-football-auction-ai/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3270, in as_default
    return _default_graph_stack.get_controller(self)
KeyboardInterrupt
````

When I run learn.py with strace (strace python learn.py) and wait until the freeze, I see the following pattern repeated over and over and over. And I see CPU utilization at 150-180% in top.
````
futex(0x1dd3ae4, FUTEX_WAIT_PRIVATE, 183469, NULL) = 0
futex(0x1dd3ab8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1c24994, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1c24990, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x1dd3ae4, FUTEX_WAIT_PRIVATE, 183471, NULL) = 0
futex(0x1dd3ab8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1c24994, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1c24990, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x1dd3ae4, FUTEX_WAIT_PRIVATE, 183473, NULL) = 0
futex(0x1dd3ab8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1c24994, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1c24990, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x1dd3ae4, FUTEX_WAIT_PRIVATE, 183475, NULL) = 0
futex(0x1dd3ab8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1c24994, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1c24990, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x1dd3ae4, FUTEX_WAIT_PRIVATE, 183477, NULL) = 0
futex(0x1dd3ab8, FUTEX_WAKE_PRIVATE, 1) = 0
````

...it keeps going, incrementing the val argument (the one after FUTEX_WAIT_PRIVATE) each time.

Maybe there is an infinite loop somewhere? Can anyone else reproduce this? I used setuptools for that repo so it should be easy to run.

**Comment by chairbender** [comment]
Major facepalm. 

I've been playing around with a debugger a little bit more thoroughly. It looks like what's going on is an infinite loop in keras-rl's core.py inside the loop at line 304. This means my gym environment (which I wrote myself) is stuck and is continually iterating without reaching a terminal state. It's just a simple infinite loop bug on my end.

**Comment by chairbender** [comment]
So I guess @rola93 might want to make sure his gym environment is not in a situation where it never finishes an episode / reaches a terminal state.
